include:
  - project: 'wizbii/gitlab-ci-library'
    file: '/templates/.package-template.yml'

variables:
  GCS_BUCKET_PATH: gs://helm-wizbii/packages
  HELM_CHART_NAME: "asqatasun"

stages:
  - test
  - release

Test:
  image: ${GCR_URL}/devops/helm:master
  stage: test
  script:
    - helm dependency build "${HELM_CHART_NAME}"
    - helm template test "${HELM_CHART_NAME}" --debug
  rules:
    - if: $CI_COMMIT_BRANCH

Package:
  image: ${GCR_URL}/devops/helm:master
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "${GCS_HELM}" > /etc/gcs.json
    - export GOOGLE_APPLICATION_CREDENTIALS=/etc/gcs.json
    - helm repo add wizbii "${GCS_BUCKET_PATH}"
    - helm repo update
    - helm package --dependency-update "${HELM_CHART_NAME}"
    - helm gcs push "${HELM_CHART_NAME}"*.tgz wizbii --force --retry

